"""init order models

Revision ID: 829110659a81
Revises: 069b6514057e
Create Date: 2025-06-19 11:47:30.910361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "829110659a81"
down_revision: Union[str, None] = "069b6514057e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute(
    #     """
    #     INSERT INTO user_groups (id, name)
    #     VALUES (1, 'admin'),
    #            (2, 'user'),
    #            (3, 'moderator') ON CONFLICT (id) DO NOTHING
    #     """
    # )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute(
    #     """
    #     DELETE
    #     FROM user_groups
    #     WHERE id IN (1, 2, 3)
    #     """
    # )
    pass
    # ### end Alembic commands ###
