x-common: &common
  build:
    context: .
    dockerfile: docker/test/Dockerfile
  env_file:
    - .env.test
  volumes:
    - ./src:/usr/src/app/src
    - ./alembic.ini:/usr/src/app/alembic.ini

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.test
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U \"$DB_USER\" -d test_db'" ]
      interval: 5s
      timeout: 5s
      retries: 10

  migrations:
    <<: *common
    command: >
      bash -c "alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy

  app:
    <<: *common
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started

  celery:
    <<: *common
    command: celery -A src.tasks_manager.celery_app worker --loglevel=info
    environment:
      PYTHONPATH: /usr/src/app/src
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started

  beat:
    <<: *common
    command: celery -A src.tasks_manager.celery_app beat --loglevel=info
    environment:
      PYTHONPATH: /usr/src/app/src
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1026:1025"
      - "8026:8025"

  stripe-cli:
    image: stripe/stripe-cli
    env_file:
      - .env.test
    command: ["stripe", "listen", "--forward-to", "http://app:8001/payments/webhook/"]
    depends_on:
      - app

volumes:
  pgdata_test: