x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  volumes:
    - ./src:/usr/src/app/src
    - ./alembic.ini:/usr/src/app/alembic.ini
  depends_on:
    - redis
    - db

services:
  app:
    <<: *common
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    environment:
      RUN_MIGRATIONS: "true"

  celery:
    <<: *common
    command: bash -c "PYTHONPATH=src celery -A tasks_manager.celery_app worker --loglevel=info"
    environment:
      RUN_MIGRATIONS: "false"

  beat:
    <<: *common
    command: bash -c "PYTHONPATH=src celery -A tasks_manager.celery_app beat --loglevel=info"
    environment:
      RUN_MIGRATIONS: "false"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: online_cinema
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
