services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\"'" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  app:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    env_file:
      - .env.test
    command: bash -c "poetry run alembic upgrade head && poetry run pytest"
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
