from src.tests.utils.fixtures import (
    registered_user,
    registered_and_activated_user,
    client_authorized_by_user,
    client_authorized_by_admin,
    client_authorized_by_moderator,
    token,
    regular_user,
    star_fixture,
    director_fixture,
    genre_fixture,
    certification_fixture,
    movie_fixture,
    cart_fixture,
    cart_item_fixture,
    purchased_movie_fixture,
)

__all__ = [
    "registered_user",
    "registered_and_activated_user",
    "client_authorized_by_user",
    "client_authorized_by_moderator",
    "client_authorized_by_admin",
    "token",
    "regular_user",
    "star_fixture",
    "director_fixture",
    "genre_fixture",
    "certification_fixture",
    "movie_fixture",
    "cart_fixture",
    "cart_item_fixture",
    "purchased_movie_fixture",
]
